### ISSUE TITLE
hqq_aten package not installed.

### ISSUE THREAD

**Issue by LeMoussel** [dvmazur/mixtral-offloading#21]
When I execute the notebook [demo.ipynb](https://github.com/dvmazur/mixtral-offloading/blob/master/notebooks/demo.ipynb), I got `hqq_aten package not installed. HQQBackend.ATEN backend will not work unless you install the hqq_aten lib in hqq/kernels.`

What does it mean? What should be installed?

**Comment by dvmazur** [comment]
Hey, @LeMoussel! This is a warning and does not affect the notebook's execution in any way. Moreover, hqq_aten is not needed as we have custom kernels for HQQ inference.

**Comment by larin92** [comment]
anyone found info on how to install `hqq_aten` though?
